### PR TITLE
Handle compat with ember-cli 0.2+

### PR DESCRIPTION
**Pull request by rondale-sc**

### CODE REVIEW

**Comment by rondale-sc** [comment]
This is rebased version of https://github.com/201-created/ember-cli-emblem-hbs-printer/pull/2.  I think that the ordering thing is still an issue though.  I'm waiting to hear back on that issue.

**Comment by mixonic** [comment]
@rondale-sc cool, holding.

**Comment by rondale-sc** [comment]
@mixonic Could you close 2, I don't have creds on this machine.

**Comment by trobrock** [comment]
How far off is this, is there anything needed to help get this through?

**Comment by rondale-sc** [comment]
@trobrock I believe there is still a bug that prevents the `setupPreprocessorRegistry` hook from ordering in this case.  

However, using the `included` as it is done on master still works.  This PR title is a bit misleading that way.  This addon already handles compat (afaik), it just doesn't do it with the newly added registry hook.

**Comment by trobrock** [comment]
So if I am having trouble getting this addon to run with ember-cli 0.2.x it is not something that would be resolved with this PR?

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-cli/pull/3464 should fix the remaining issue with this pull request. 

@rondale-sc - Can you rebase to get this ready?

**Comment by rondale-sc** [comment]
Sounds good.  Just tested against  ember-cli/ember-cli#3464 and it worked.  going to rebase

**Comment by rondale-sc** [comment]
Rebase wasn't necessary, still up to date.  This should be good to go.  

@rwjblue Is there any concern with letting people know that this won't work with 0.2.0-beta.1?

**Comment by rwjblue** [comment]
@rondale-sc - I don't think so, but its up to @mixonic.

@mixonic - Ember CLI 0.2.0 final is out now, so I think this is good to go (the issues @rondale-sc was hitting earlier are finally ironed out).

**Comment by rwjblue** [comment]
@rondale-sc - Just noticed this is still labeled as `WIP`, mind amending the commit and pull request title?

**Comment by rondale-sc** [comment]
@rwjblue Done.  :)

**Comment by trobrock** [comment]
Thanks guys, just confirmed with 0.2.0 and this PR I can get emblem working.

**Comment by mixonic** [comment]
amazing, thanks guys.

**Comment by mixonic** [comment]
Really, really appreciate the effort and time. :tada:

**Comment by rondale-sc** [comment]
Woot!

**Pull request merged**
